export const mockBots = [
  {
    id: "bot-001",
    name: "FlamengoBot Alpha",
    status: "active" as const,
    event: "Flamengo x Palmeiras — Libertadores",
    account: "conta.joao@gmail.com",
    lastRun: "há 2 min",
    health: 98,
    sector: "Norte Superior",
    qty: 2,
    proxy: "BR-SP-01",
    interval: "30s",
    createdAt: "15/04/2025",
    monitoredSince: "16/04/2025 08:30",
    logs: [
      { time: "14:52:31", type: "info", msg: "Monitorando disponibilidade...", status: "ok" },
      { time: "14:52:01", type: "cart", msg: "Ingresso adicionado ao carrinho: Norte Superior R$180", status: "success" },
      { time: "14:51:44", type: "info", msg: "Setor Norte Superior encontrado com 3 ingressos disponíveis", status: "ok" },
      { time: "14:51:20", type: "proxy", msg: "IP rotacionado → BR-SP-01 (186.xxx.xxx.12)", status: "ok" },
      { time: "14:50:55", type: "info", msg: "Tentativa de acesso à página de ingressos", status: "ok" },
      { time: "14:50:30", type: "warning", msg: "Rate limit detectado. Aguardando 30s...", status: "warn" },
      { time: "14:50:00", type: "info", msg: "Bot iniciado com sucesso", status: "ok" },
    ],
  },
  {
    id: "bot-002",
    name: "CorinthiansBot X2",
    status: "active" as const,
    event: "Corinthians x São Paulo — Brasileirão",
    account: "conta.maria@hotmail.com",
    lastRun: "há 5 min",
    health: 85,
    sector: "Sul Gold",
    qty: 4,
    proxy: "BR-RJ-02",
    interval: "45s",
    createdAt: "14/04/2025",
    monitoredSince: "15/04/2025 10:00",
    logs: [
      { time: "14:49:10", type: "info", msg: "Verificando estoque no setor Sul Gold...", status: "ok" },
      { time: "14:48:50", type: "error", msg: "Sessão expirada. Reautenticando conta...", status: "error" },
      { time: "14:48:30", type: "info", msg: "Autenticação renovada com sucesso", status: "ok" },
      { time: "14:47:00", type: "info", msg: "Monitorando evento: Corinthians x São Paulo", status: "ok" },
    ],
  },
  {
    id: "bot-003",
    name: "PalmeirasSniperV3",
    status: "paused" as const,
    event: "Palmeiras x Boca Juniors — Libertadores",
    account: "conta.lucas@gmail.com",
    lastRun: "há 1h",
    health: 60,
    sector: "Camarote Premium",
    qty: 2,
    proxy: "BR-SP-03",
    interval: "60s",
    createdAt: "13/04/2025",
    monitoredSince: "—",
    logs: [
      { time: "13:30:00", type: "info", msg: "Bot pausado pelo usuário", status: "warn" },
      { time: "13:25:10", type: "info", msg: "Última verificação concluída sem resultado", status: "ok" },
    ],
  },
  {
    id: "bot-004",
    name: "GremioRapidBot",
    status: "error" as const,
    event: "Grêmio x Internacional — Gauchão",
    account: "conta.ana@gmail.com",
    lastRun: "há 20 min",
    health: 12,
    sector: "Arena Sul",
    qty: 2,
    proxy: "BR-RS-01",
    interval: "30s",
    createdAt: "12/04/2025",
    monitoredSince: "—",
    logs: [
      { time: "14:30:00", type: "error", msg: "Falha crítica: CAPTCHA não resolvido após 3 tentativas", status: "error" },
      { time: "14:29:30", type: "error", msg: "Tentativa 3/3 de resolver CAPTCHA falhou", status: "error" },
      { time: "14:28:00", type: "warning", msg: "CAPTCHA detectado na página de checkout", status: "warn" },
    ],
  },
  {
    id: "bot-005",
    name: "SaoPauloAutoFill",
    status: "waiting" as const,
    event: "São Paulo x River Plate — Sul-Americana",
    account: "conta.pedro@outlook.com",
    lastRun: "Aguardando abertura",
    health: 100,
    sector: "Morumbi Superior",
    qty: 3,
    proxy: "BR-SP-05",
    interval: "15s",
    createdAt: "16/04/2025",
    monitoredSince: "18/04/2025 12:00",
    logs: [
      { time: "12:00:00", type: "info", msg: "Bot configurado. Aguardando abertura das vendas em 20/04/2025 às 10:00", status: "ok" },
    ],
  },
]

export const mockEvents = [
  {
    id: "ev-001",
    home: "Flamengo",
    away: "Palmeiras",
    competition: "Libertadores 2025",
    date: "22/04/2025",
    time: "21:30",
    status: "monitoring" as const,
    bots: 2,
    priority: "high" as const,
  },
  {
    id: "ev-002",
    home: "Corinthians",
    away: "São Paulo",
    competition: "Brasileirão Série A",
    date: "25/04/2025",
    time: "16:00",
    status: "monitoring" as const,
    bots: 1,
    priority: "medium" as const,
  },
  {
    id: "ev-003",
    home: "Grêmio",
    away: "Internacional",
    competition: "Gauchão 2025",
    date: "27/04/2025",
    time: "17:00",
    status: "error" as const,
    bots: 1,
    priority: "low" as const,
  },
  {
    id: "ev-004",
    home: "São Paulo",
    away: "River Plate",
    competition: "Sul-Americana 2025",
    date: "30/04/2025",
    time: "19:00",
    status: "scheduled" as const,
    bots: 1,
    priority: "high" as const,
  },
  {
    id: "ev-005",
    home: "Palmeiras",
    away: "Boca Juniors",
    competition: "Libertadores 2025",
    date: "01/05/2025",
    time: "21:30",
    status: "scheduled" as const,
    bots: 1,
    priority: "high" as const,
  },
]

export const mockCarts = [
  {
    id: "cart-001",
    account: "conta.joao@gmail.com",
    event: "Flamengo x Palmeiras — Libertadores",
    sessionStatus: "active" as const,
    items: [
      {
        id: "item-001",
        name: "Ingresso Norte Superior",
        sector: "Norte Superior",
        type: "Inteira",
        qty: 2,
        unitPrice: 180.0,
        status: "reserved" as const,
      },
    ],
    expiresAt: "14 min",
    lastUpdate: "há 2 min",
    readyForCheckout: true,
    expiring: false,
  },
  {
    id: "cart-002",
    account: "conta.maria@hotmail.com",
    event: "Corinthians x São Paulo — Brasileirão",
    sessionStatus: "active" as const,
    items: [
      {
        id: "item-002",
        name: "Ingresso Sul Gold",
        sector: "Sul Gold",
        type: "Inteira",
        qty: 2,
        unitPrice: 220.0,
        status: "reserved" as const,
      },
      {
        id: "item-003",
        name: "Ingresso Sul Gold",
        sector: "Sul Gold",
        type: "Meia-Entrada",
        qty: 2,
        unitPrice: 110.0,
        status: "reserved" as const,
      },
    ],
    expiresAt: "3 min",
    lastUpdate: "há 5 min",
    readyForCheckout: false,
    expiring: true,
  },
  {
    id: "cart-003",
    account: "conta.lucas@gmail.com",
    event: "Palmeiras x Boca Juniors — Libertadores",
    sessionStatus: "inactive" as const,
    items: [],
    expiresAt: "—",
    lastUpdate: "há 1h",
    readyForCheckout: false,
    expiring: false,
  },
]

export const mockActivityLog = [
  { id: 1, time: "14:52:01", type: "cart", msg: "Ingresso adicionado ao carrinho: FlamengoBot Alpha", icon: "cart" },
  { id: 2, time: "14:51:20", type: "proxy", msg: "IP rotacionado em FlamengoBot Alpha → BR-SP-01", icon: "proxy" },
  { id: 3, time: "14:50:30", type: "warning", msg: "Rate limit em FlamengoBot Alpha. Aguardando...", icon: "warning" },
  { id: 4, time: "14:48:50", type: "error", msg: "Sessão expirada em CorinthiansBot X2 — reautenticando", icon: "error" },
  { id: 5, time: "14:48:30", type: "success", msg: "Conta conta.maria@hotmail.com autenticada com sucesso", icon: "auth" },
  { id: 6, time: "14:30:00", type: "error", msg: "Falha crítica no GremioRapidBot: CAPTCHA detectado", icon: "error" },
  { id: 7, time: "14:00:00", type: "start", msg: "FlamengoBot Alpha iniciado com sucesso", icon: "start" },
  { id: 8, time: "13:30:00", type: "pause", msg: "PalmeirasSniperV3 pausado pelo usuário", icon: "pause" },
]
